trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Backend
- script: |
    cd backend
    npm install
  displayName: 'Install Backend Dependencies'


# Code Analysis
- script: |
    cd backend
    npm run lint
  displayName: 'Code Analysis - ESLint'

# Unit Tests
- script: |
    cd backend
    npm test
  displayName: 'Unit Tests - Jest'

  
# Frontend
- script: |
    cd frontend
    npm install
  displayName: 'Install Frontend Dependencies'

# Build Frontend
- script: |
    cd frontend
    npm run build
  displayName: 'Build Frontend'

# Create deployment package
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/backend'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/mern-app.zip'
    replaceExistingArchive: true
  displayName: 'Create ZIP Package'

# Publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'mern-app'
  displayName: 'Publish Artifact'

# Deploy to Azure App Service
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'mern-dev-azure'
    appType: 'webAppLinux'
    appName: 'mern-workout-app'
    package: '$(Build.ArtifactStagingDirectory)/mern-app.zip'